const designationsList: string[] = [
  "Manager",
  "Intern Software-Developer",
  "Assistant Software-Developer",
  "Associate Software-Developer",
  "Intern Frontend-Developer",
  "Senior Frontend-Developer",
  "Senior Backend-Developer",
  "Intern Backend-Developer",
  "Junior Backend-Developer",
  "Junior Frontend-Developer",
  "Senior Designer",
  "Junior Designer",
  "Inter Designer",
  "Intern Quality-Analyst",
  "Senior Quality-Analyst",
  "Junior Quality-Analyst",
  "Senior HR",
  "Junior HR",
  "Intern HR",
  "Software Engineer",
  "Software Architect",
  "Systems analyst",
  "Project Manager",
  "Web Developer",
  "Lead Developer",
  "Software developer",
  "Network Administrator",
  "Database Administrator",
  "CEO",
  "Director",
  "UX Designer",
  "Data Scientist",
  "BlockChain Developer",
  "IT manager",
  "Technical lead",
  "DevOps engineer",
  "Artificial intelligence engineer",
  "IT security analyst",
  "COO",
  "Director",
  "Sales Engineer",

  // Add more designations as needed
];

export default designationsList;

