const designationsList: string[] = [
  "CEO",
  "COO",
  "CTO",
  "BA Head",
  "Product Head",
  "Senior HR",
  "TPM",
  "Team Lead",
  "Senior Frontend-Developer",
  "Senior Backend-Developer",
  "Senior Quality-Analyst",
  "Senior Business-Analyst",
  "Senior Designer",
  "Senior IT- Developer",
  "Assistant Software-Developer",
  "Assistant IT- Developer",
  "Associate Software-Developer",
  "Junior Backend-Developer",
  "Junior Frontend-Developer",
  "Junior Quality-Analyst",
  "Junior Designer",
  "Junior HR",
  "Junior Business-Analyst",
  "Junior IT- Developer",
  "Inter Designer",
  "Intern Software-Developer",
  "Intern Frontend-Developer",
  "Intern Backend-Developer",
  "Intern Quality-Analyst",
  "Intern Business-Analyst",
  "Intern HR",
  "Intern IT- Developer",
  // Add more designations as needed
];

export default designationsList;

